# Generated by Django 5.2.6 on 2025-10-03 20:05

import app_gestion_alimentos.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id_almacen', models.AutoField(primary_key=True, serialize=False)),
                ('desc_almacen', models.CharField(default='?', max_length=400)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'almacenes',
            },
        ),
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id_medida', models.AutoField(primary_key=True, serialize=False)),
                ('desc_medida', models.CharField(default='?', max_length=150, validators=[django.core.validators.MinLengthValidator(2)])),
            ],
            options={
                'db_table': 'medidas',
            },
        ),
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id_alimento', models.AutoField(primary_key=True, serialize=False)),
                ('imagen_alimento', models.ImageField(blank=True, null=True, upload_to=app_gestion_alimentos.models.alimento_imagen_ruta)),
                ('desc_alimento', models.CharField(default='?', max_length=400)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('almacen_perteneciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_alimentos', to='app_gestion_alimentos.almacen')),
                ('medida_alimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_medida', to='app_gestion_alimentos.medida')),
            ],
            options={
                'db_table': 'alimentos',
            },
        ),
    ]
